# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven

    - name: Install packages
      run: mvn clean install

    - name: Build with Maven
      run: mvn -B verify --file pom.xml

    - name: Run tests
      run: mvn verify -Dcucumber.tags="not @wip"

    - name: Test Report Generation
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: Serenity Report                 # Name of the folder
        path: target/site/serenity/           # Path to test results
